apiVersion: v2
name: ingress
description: A Helm chart for Ingress Controller
type: application
version: 0.1.0
appVersion: 1.16.0
dependencies:
  - name: ingress-nginx
    version: 4.6.1
    repository: https://kubernetes.github.io/ingress-nginx
keywords:
  - ingress
  - nginx
  - api-gateway
home: https://github.com/JoePalmeras66/helm-repo/tree/master
maintainers:
  - name: Joe Palmeras
    url: https://github.com/JoePalmeras66
