ingress:
  name: ingress-service
  replicaCount: 1
  annotations: 
    class: nginx
  hosts:
    - host: chart-example.local
      paths: 
        - pathType: Prefix
          backend:
            service:
              name: serviceName
              port: 8080
          path: /
