ingress:
  name: ingress-service
  namespace: default
  replicaCount: 1
  annotations: 
    class: nginx
  hosts:
    - host: chart-example.local
      paths: 
        - pathType: Prefix
          backend:
            serviceName: serviceName
            servicePort: 8080
          path: /
