ingress:
  name: ingress-service
  namespace: default
  replicaCount: 1
  annotations: 
    class: nginx
#    issuer: letsencrypt-staging
  tls:
    - secretName: chart-example-tls
      hosts: 
        - chart-example.local
  hosts:
    - host: chart-example.local
      paths: 
        - pathType: Prefix
          backend:
            serviceName: serviceName
            servicePort: 8080
          path: /
